! pip install requests load_dotenev
! pip install

In [1]:
import requests # Importing the requests library for making HTTP requests
import pandas as pd # Importing pandas for data manipulation and analysis
import json # Importing json for handling JSON data
import os # Importing os for operating system dependent functionality
from dotenv import load_dotenv # Importing load_dotenv to load environment variables from a .env file

In [2]:
load_dotenv()
# Loading environment variables from a .env file
# This allows us to use sensitive information like API keys without hardcoding them in the script.

# Fetching the Etherscan API key from environment variables
ETHERSCAN_API_KEY = os.getenv('ETHERSCAN_API_KEY') 

# Fetching the CoinPaprika API key from environment variables
COINGECKO_API_KEY = os.getenv('COINGECKO_API_KEY') 

if not ETHERSCAN_API_KEY or not COINGECKO_API_KEY:
    raise ValueError("Please set the ETHERSCAN_API_KEY and COINGECKO_API_KEY environment variables.")

In [3]:
etherscan_url = 'https://api.etherscan.io/v2/api' # Etherscan API endpoint we will be using

In [4]:
# We structure parameters as a dictionary to allow for easy expansion in the future
# If we need to add more parameters, we can simply add them to this dictionary

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'account', # Module for account-related actions
    'action':'balance', # Action to get the account balance
    'address':'0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae',
    'tag':'latest', # Tag to specify the latest block
    'apikey':ETHERSCAN_API_KEY # API Key
}

response = requests.get(url=etherscan_url, params=params) # Making a GET request to the Etherscan API with the specified parameters
response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx status codes)
data = response.json() # Parsing the JSON response from the API

In [ ]:
# Display the data
print(f'API Response:\n{json.dumps(data, indent=4)}') 

# Print the JSON data with an indentation of 4 spaces

API Response:
{
    "status": "1",
    "message": "OK",
    "result": "181774355015033119539577"
}

In [6]:
type(data) # Display the type of the data variable to confirm it's a dictionary

dict

In [7]:
data.keys() # Display the keys of the data dictionary to understand its structure

dict_keys(['status', 'message', 'result'])

In [ ]:
# Convert the balance from Wei to Ether
# Etherscan returns balances in Wei, which is the smallest unit of Ether
# 1 Ether = 10^18 Wei, so we divide the balance in Wei by 10^18 to get the balance in Ether

balance_wei = int(data['result']) # Extracting the balance in Wei from the response
balance_ether = balance_wei / 10**18 # Converting Wei to Ether
print(f'Balance in Ether: {balance_ether}') # Displaying the balance in Ether

Balance in Ether: 183774.35474609083

In [8]:
# Get Transaction status by Transaction Hash

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'transaction', # Module for transaction-related actions
    'action':'gettxreceiptstatus', # Action to get the account balance
    'txhash':'0x4ea4d96a92ce1266f96d7bb60577f46c90eff421a242bff3d9ac64fbd00d0870',
    'apikey':ETHERSCAN_API_KEY # API Key
}

response = requests.get(url=etherscan_url, params=params) # Making a GET request to the Etherscan API with the specified parameters
response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx status codes)
data = response.json() # Parsing the JSON response from the API

In [9]:
# Display the data
print(f'API Response:\n{json.dumps(data, indent=4)}')

API Response:
{
    "status": "1",
    "message": "OK",
    "result": {
        "status": ""
    }
}

### Get "Normal" transactions for a specific address

In [ ]:
# Normal transactions are those that are not contract interactions or internal transactions
# They are typically user-initiated transactions that transfer Ether or tokens between addresses.

# This returns a max of 1000 transactions per request, so if you need more, you will have to paginate through the results.

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'account', # Module for account-related actions
    'action':'txlist', # Action to get the transaction list
    'address':'0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae', # Address to get transactions for
    'startblock':0, # Starting block number (0 for the earliest block)
    'endblock':99999999, # Ending block number (99999999 for the latest block)
    'sort':'asc', # Sort order (asc for ascending)
    'apikey':ETHERSCAN_API_KEY # API Key
}

response = requests.get(url=etherscan_url, params=params) # Making a GET request to the Etherscan API with the specified parameters
response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx status codes)
data = response.json() # Parsing the JSON response from the API

# Display the data
print(f'API Response:\n{json.dumps(data, indent=4)}')

API Response:
{
    "status": "1",
    "message": "OK",
    "result": [
        {
            "blockNumber": "54092",
            "timeStamp": "1439048640",
            "hash": "0x9c81f44c29ff0226f835cd0a8a2f2a7eca6db52a711f8211b566fd15d3e0e8d4",
            "nonce": "0",
            "blockHash": "0xd3cabad6adab0b52eb632c386ea194036805713682c62cb589b5abcd76de2159",
            "transactionIndex": "0",
            "from": "0x5abfec25f74cd88437631a7731906932776356f9",
            "to": "",
            "value": "11901464239480000000000000",
            "gas": "2000000",
            "gasPrice": "10000000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0x6060604052600760018181557305096a47749d8bfab0a90c1bb7a95115dbe4cea6600355737c56d94ebeccb769524379c450873519a9d805ff600490815573cda0ad7542e30bf520652a05056ebe0105c7e49a60055573775e18be7a50a0abb8a4e82b1bd697d79f31fe0460065573063dd253c8da4ea9b12105781c9611b8297f5d1490925573036c8cecce8d8bbf0831d840d7f29c9e3ddefa63600855733fb1cd2cd96c6d5c0b5eb3322d807b34482481d4600955683635c9adc5dea0000091905b600781116100f457806101026000600283610100811015610002570154815260209190915260409020556001016100c2565b506000556101058190556201518042046101075550610f33806101186000396000f300606060405236156100b95760e060020a6000350463173825d9811461010b5780632f54bf6e1461015b5780634123cb6b146101835780635c52c2f51461018c5780637065cb48146101b2578063746c9171146101db578063797af627146101e4578063b20d30a9146101f7578063b61d27f614610220578063b75c7dc614610241578063ba51a6df14610270578063c2cf732614610299578063cbf0b0c0146102d7578063f00d4b5d14610300578063f1736d861461032e575b61033860003411156101095760408051600160a060020a033316815234602082015281517fe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c929181900390910190a15b565b6103386004356000600036604051808383808284375050509081018190039020905061063d815b600160a060020a03331660009081526101026020526040812054818082811415610bb357610d0b565b61033a6004355b600160a060020a03811660009081526101026020526040812054115b919050565b61033a60015481565b610338600036604051808383808284375050509081018190039020905061078e81610132565b61033860043560003660405180838380828437505050908101819003902090506105b581610132565b61033a60005481565b61033a6004355b6000816109f181610132565b610338600435600036604051808383808284375050509081018190039020905061078281610132565b61033a6004803590602480359160443591820191013560006107ad33610162565b610338600435600160a060020a0333166000908152610102602052604081205490808281141561034c576103cb565b61033860043560003660405180838380828437505050908101819003902090506106fc81610132565b61033a600435602435600082815261010360209081526040808320600160a060020a0385168452610102909252822054828181141561075557610779565b610338600435600036604051808383808284375050509081018190039020905061079c81610132565b6103386004356024356000600036604051808383808284375050509081018190039020905061045681610132565b61033a6101055481565b005b60408051918252519081900360200190f35b50506000828152610103602052604081206001810154600284900a9290831611156103cb5780546001828101805492909101835590839003905560408051600160a060020a03331681526020810186905281517fc7fb647e59b18047309aa15aad418e5d7ca96d173ad704f1031a2c3d7591734b929181900390910190a15b50505050565b600160a060020a03831660028361010081101561000257508301819055600160a060020a03851660008181526101026020908152604080832083905584835291829020869055815192835282019290925281517fb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c929181900390910190a1505b505050565b156103cb5761046483610162565b1561046f5750610451565b600160a060020a0384166000908152610102602052604081205492508214156104985750610451565b6103d15b6101045460005b81811015610e5857610104805461010891600091849081101561000257600080516020610f1383398151915201548252506020918252604081208054600160a060020a0319168155600181018290556002810180548382559083528383209193610edd92601f92909201048101906109d9565b60018054810190819055600160a060020a038316906002906101008110156100025790900160005081905550600160005054610102600050600084600160a060020a03168152602001908152602001600020600050819055507f994a936646fe87ffe4f1e469d3d6aa417d6b855598397f323de5b449f765f0c3826040518082600160a060020a0316815260200191505060405180910390a15b505b50565b156105b0576105c382610162565b156105ce57506105b2565b6105d661049c565b60015460fa90106105eb576105e9610600565b505b60015460fa901061051657506105b2565b6106ba5b600060015b6001548110156109ed575b600154811080156106305750600281610100811015610002570154600014155b15610d1357600101610610565b1561045157600160a060020a03831660009081526101026020526040812054925082141561066b57506105b0565b600160016000505403600060005054111561068657506105b0565b600060028361010081101561000257508301819055600160a060020a038416815261010260205260408120556105fc61049c565b5060408051600160a060020a038516815290517f58619076adf5bb0943d100ef88d52d7c3fd691b19d3a9071b555b651fbf418da9181900360200190a1505050565b156105b05760015482111561071157506105b2565b600082905561071e61049c565b6040805183815290517facbdb084c721332ac59f9b8e392196c9eb0e4932862da8eb9beaf0dad4f550da9181900360200190a15050565b506001820154600282900a908116600014156107745760009350610779565b600193505b50505092915050565b156105b0575061010555565b156105b25760006101065550565b156105b05781600160a060020a0316ff5b156109c9576107c1846000610ded33610162565b1561087d577f92ca3a80853e6663fa31fa10b99225f18d4902939b4c53a9caae9043f6efd00433858786866040518086600160a060020a0316815260200185815260200184600160a060020a031681526020018060200182810382528484828181526020019250808284378201915050965050505050505060405180910390a184600160a060020a03168484846040518083838082843750505090810191506000908083038185876185025a03f150600093506109c992505050565b600036436040518084848082843750505090910190815260405190819003602001902091506108ad9050816101eb565b1580156108d0575060008181526101086020526040812054600160a060020a0316145b156109c95760008181526101086020908152604082208054600160a060020a03191688178155600181018790556002018054858255818452928290209092601f019190910481019084908682156109d1579182015b828111156109d1578235826000505591602001919060010190610925565b50507f1733cbb53659d713b79580f79f3f9ff215f78a7c7aa45890f3b89fc5cddfbf328133868887876040518087815260200186600160a060020a0316815260200185815260200184600160a060020a03168152602001806020018281038252848482818152602001925080828437820191505097505050505050505060405180910390a15b949350505050565b506109439291505b808211156109ed57600081556001016109d9565b5090565b15610ba05760008381526101086020526040812054600160a060020a031614610ba05760408051600091909120805460018201546002929092018054600160a060020a0392909216939091819083908015610a7157820191906000526020600020905b815481529060010190602001808311610a5457829003601f168201915b505091505060006040518083038185876185025a03f150505060008481526101086020908152604080519281902080546001820154600160a060020a033381811688529587018b905293860181905292166060850181905260a06080860181815260029390930180549187018290527fe7c957c06e9a662c1a6c77366179f5b702b97651dc28eee7d5bf1dff6e40bb4a975094958a959293909160c083019084908015610b4357820191906000526020600020905b815481529060010190602001808311610b2657829003601f168201915b5050965050505050505060405180910390a160008381526101086020908152604082208054600160a060020a031916815560018101839055600281018054848255908452828420919392610ba692601f92909201048101906109d9565b50919050565b505050600191505061017e565b60008581526101036020526040812080549093501415610c3b576000805483556001838101919091556101048054918201808255828015829011610c0a57818360005260206000209182019101610c0a91906109d9565b50505060028301819055610104805487929081101561000257600091909152600080516020610f1383398151915201555b506001810154600283900a90811660001415610d0b5760408051600160a060020a03331681526020810187905281517fe1c52dc63b719ade82e8bea94cc41a0d5d28e4aaf536adb5e9cccc9ff8c1aeda929181900390910190a1815460019011610cf8576000858152610103602052604090206002015461010480549091908110156100025760406000908120600080516020610f138339815191529290920181905580825560018281018290556002909201559450610d0b9050565b8154600019018255600182018054821790555b505050919050565b5b60018054118015610d3657506001546002906101008110156100025701546000145b15610d4a5760018054600019019055610d14565b60015481108015610d6d5750600154600290610100811015610002570154600014155b8015610d8757506002816101008110156100025701546000145b15610de857600154600290610100811015610002578101549082610100811015610002578101919091558190610102906000908361010081101561000257810154825260209290925260408120929092556001546101008110156100025701555b610605565b1561017e5761010754610e035b62015180420490565b1115610e1c57600061010655610e17610dfa565b610107555b6101065480830110801590610e3a5750610106546101055490830111155b15610e505750610106805482019055600161017e565b50600061017e565b6105b06101045460005b81811015610ee85761010480548290811015610002576000918252600080516020610f13833981519152015414610ed557610104805461010391600091849081101561000257600080516020610f1383398151915201548252506020919091526040812081815560018101829055600201555b600101610e62565b5050506001016104a3565b610104805460008083559190915261045190600080516020610f13833981519152908101906109d956004c0be60200faa20559308cb7b5a1bb3255c16cb1cab91f525b5ae7a03d02fabe",
            "contractAddress": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "cumulativeGasUsed": "1436963",
            "gasUsed": "1436963",
            "confirmations": "23044078",
            "methodId": "0x60606040",
            "functionName": ""
        },
        {
            "blockNumber": "65204",
            "timeStamp": "1439232889",
            "hash": "0x98beb27135aa0a25650557005ad962919d6a278c4b3dde7f4f6a3a1e65aa746c",
            "nonce": "0",
            "blockHash": "0x373d339e45a701447367d7b9c7cef84aab79c2b2714271b908cda0ab3ad0849b",
            "transactionIndex": "0",
            "from": "0x3fb1cd2cd96c6d5c0b5eb3322d807b34482481d4",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "122261",
            "gasPrice": "50000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d000000000000000000000000036c8cecce8d8bbf0831d840d7f29c9e3ddefa63000000000000000000000000c5a96db085dda36ffbe390f455315d30d6d3dc52",
            "contractAddress": "",
            "cumulativeGasUsed": "122207",
            "gasUsed": "122207",
            "confirmations": "23032966",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "65342",
            "timeStamp": "1439235315",
            "hash": "0x621de9a006b56c425d21ee0e04ab25866fff4cf606dd5d03cf677c5eb2172161",
            "nonce": "1",
            "blockHash": "0x889d18b8791f43688d07e0b588e94de746a020d4337c61e5285cd97556a6416e",
            "transactionIndex": "0",
            "from": "0x3fb1cd2cd96c6d5c0b5eb3322d807b34482481d4",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "122269",
            "gasPrice": "50000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "122207",
            "gasUsed": "122207",
            "confirmations": "23032828",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "68413",
            "timeStamp": "1439287454",
            "hash": "0x1c1fb39d78d2ddfbba1ebd38076ccf54b8aaf3910839e0d0d737c61b1e264e00",
            "nonce": "0",
            "blockHash": "0x822cb48acc3c839264ec9cb247600e05089d72f8aea5ff133dd73b7028062a9a",
            "transactionIndex": "0",
            "from": "0x063dd253c8da4ea9b12105781c9611b8297f5d14",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "150000",
            "gasPrice": "60137282256",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d000000000000000000000000036c8cecce8d8bbf0831d840d7f29c9e3ddefa63000000000000000000000000c5a96db085dda36ffbe390f455315d30d6d3dc52",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23029757",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "68425",
            "timeStamp": "1439287671",
            "hash": "0xb8ce46e64f5fbaec38073e592e00bce29f17cbcccc3e88e29c3f67163787e619",
            "nonce": "1",
            "blockHash": "0xaf01ce827008d1a1ee157ddb06866bc7e01a9375d1bdd637f192893393c13471",
            "transactionIndex": "0",
            "from": "0x063dd253c8da4ea9b12105781c9611b8297f5d14",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "150000",
            "gasPrice": "60251851460",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23029745",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "68779",
            "timeStamp": "1439293693",
            "hash": "0xb9d70845c2abab8b548a1568d1bef653904f3a48073ec1a91e46cfe0414c286e",
            "nonce": "0",
            "blockHash": "0xef4e415e40fd28e0214401f9254b86041bad705f26c2edee54fe46d564c43f66",
            "transactionIndex": "0",
            "from": "0x7c56d94ebeccb769524379c450873519a9d805ff",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "36740",
            "gasPrice": "50000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d000000000000000000000000036c8cecce8d8bbf0831d840d7f29c9e3ddefa63000000000000000000000000c5a96db085dda36ffbe390f455315d30d6d3dc52",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23029391",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "68783",
            "timeStamp": "1439293737",
            "hash": "0xd90ce562962445bc66a7e0ce205219fc1307b4e577ff55f8728494a314fffc0a",
            "nonce": "1",
            "blockHash": "0x4aedaa6d1e3c3e43d3c94d60774df3f46f7a137aa55c1c103357c6641d7cca71",
            "transactionIndex": "0",
            "from": "0x7c56d94ebeccb769524379c450873519a9d805ff",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "36780",
            "gasPrice": "50000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23029387",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "69853",
            "timeStamp": "1439310832",
            "hash": "0xcb1316911442ff0e9685a822d5a449eb875ad2d88a1483ccbc1e4c26c0be9f9e",
            "nonce": "0",
            "blockHash": "0x163eeb196fdc71abb077583cd46a1b7cb750aeae00cf8fb885899d23bb4f4a7c",
            "transactionIndex": "0",
            "from": "0x775e18be7a50a0abb8a4e82b1bd697d79f31fe04",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "1000000",
            "gasPrice": "58039008293",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d000000000000000000000000036c8cecce8d8bbf0831d840d7f29c9e3ddefa63000000000000000000000000c5a96db085dda36ffbe390f455315d30d6d3dc52",
            "contractAddress": "",
            "cumulativeGasUsed": "70738",
            "gasUsed": "70738",
            "confirmations": "23028317",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "69928",
            "timeStamp": "1439312058",
            "hash": "0x75bd4a93c0c79b72eb6af8990b43bc3632599cf9d9fd9c3028f01283c9b069f2",
            "nonce": "1",
            "blockHash": "0xb87e37ff0182a26878cdafd50ea8093641ccdbfb47974a99778aa3c46334fa87",
            "transactionIndex": "0",
            "from": "0x775e18be7a50a0abb8a4e82b1bd697d79f31fe04",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "1000000",
            "gasPrice": "55030666693",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "122207",
            "gasUsed": "122207",
            "confirmations": "23028242",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "70013",
            "timeStamp": "1439313339",
            "hash": "0x97cede8fa9f55e4417eb8129bdfe74e7d7d1669f1054c595a821be6621eec7c8",
            "nonce": "3",
            "blockHash": "0xee4c89cc692c33939bf919e7b820670542a26f71968fff4ef46bd30f7d5658ac",
            "transactionIndex": "0",
            "from": "0x7c56d94ebeccb769524379c450873519a9d805ff",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "36740",
            "gasPrice": "50000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23028157",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "70128",
            "timeStamp": "1439315099",
            "hash": "0x6d013bd6ac31a97cf149b928c6b7b6a649e325b178768c6b4e60632b8ec3b479",
            "nonce": "0",
            "blockHash": "0xc37b67a734e4e29074cfc9ad1252e88b174393baba5071a23a1450ab7662ddc9",
            "transactionIndex": "0",
            "from": "0xc5a96db085dda36ffbe390f455315d30d6d3dc52",
            "to": "0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae",
            "value": "0",
            "gas": "36740",
            "gasPrice": "500000000000",
            "isError": "0",
            "txreceipt_status": "",
            "input": "0xf00d4b5d00000000000000000000000005096a47749d8bfab0a90c1bb7a95115dbe4cea60000000000000000000000005ed8cee6b63b1c6afce3ad7c92f4fd7e1b8fad9f",
            "contractAddress": "",
            "cumulativeGasUsed": "36733",
            "gasUsed": "36733",
            "confirmations": "23028042",
            "methodId": "0xf00d4b5d",
            "functionName": "changeOwner(address _from, address _to)"
        },
        {
            "blockNumber": "74115",
            "timeStamp": "1439380665",

In [11]:
# Let's convert the transactions from the API response into a pandas DataFrame for easier manipulation and analysis

transactions = pd.DataFrame(data['result']) # Converting the transactions to a pandas DataFrame
transactions['timeStamp'] = pd.to_datetime(transactions['timeStamp'], unit='s') # Converting the timestamp from Unix time to a human-readable format

transactions.head()

C:\Users\PC\AppData\Local\Temp\ipykernel_18320\3219569300.py:4: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  transactions['timeStamp'] = pd.to_datetime(transactions['timeStamp'], unit='s') # Converting the timestamp from Unix time to a human-readable format

,blockNumber,timeStamp,hash,nonce,blockHash,transactionIndex,from,to,value,gas,gasPrice,isError,txreceipt_status,input,contractAddress,cumulativeGasUsed,gasUsed,confirmations,methodId,functionName
0,54092,2015-08-08 15:44:00,0x9c81f44c29ff0226f835cd0a8a2f2a7eca6db52a711f...,0,0xd3cabad6adab0b52eb632c386ea194036805713682c6...,0,0x5abfec25f74cd88437631a7731906932776356f9,,11901464239480000000000000,2000000,10000000000000,0,,0x6060604052600760018181557305096a47749d8bfab0...,0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae,1436963,1436963,23044078,0x60606040,
1,65204,2015-08-10 18:54:49,0x98beb27135aa0a25650557005ad962919d6a278c4b3d...,0,0x373d339e45a701447367d7b9c7cef84aab79c2b27142...,0,0x3fb1cd2cd96c6d5c0b5eb3322d807b34482481d4,0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae,0,122261,50000000000,0,,0xf00d4b5d000000000000000000000000036c8cecce8d...,,122207,122207,23032966,0xf00d4b5d,"changeOwner(address _from, address _to)"
2,65342,2015-08-10 19:35:15,0x621de9a006b56c425d21ee0e04ab25866fff4cf606dd...,1,0x889d18b8791f43688d07e0b588e94de746a020d4337c...,0,0x3fb1cd2cd96c6d5c0b5eb3322d807b34482481d4,0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae,0,122269,50000000000,0,,0xf00d4b5d00000000000000000000000005096a47749d...,,122207,122207,23032828,0xf00d4b5d,"changeOwner(address _from, address _to)"
3,68413,2015-08-11 10:04:14,0x1c1fb39d78d2ddfbba1ebd38076ccf54b8aaf3910839...,0,0x822cb48acc3c839264ec9cb247600e05089d72f8aea5...,0,0x063dd253c8da4ea9b12105781c9611b8297f5d14,0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae,0,150000,60137282256,0,,0xf00d4b5d000000000000000000000000036c8cecce8d...,,36733,36733,23029757,0xf00d4b5d,"changeOwner(address _from, address _to)"
4,68425,2015-08-11 10:07:51,0xb8ce46e64f5fbaec38073e592e00bce29f17cbcccc3e...,1,0xaf01ce827008d1a1ee157ddb06866bc7e01a9375d1bd...,0,0x063dd253c8da4ea9b12105781c9611b8297f5d14,0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae,0,150000,60251851460,0,,0xf00d4b5d00000000000000000000000005096a47749d...,,36733,36733,23029745,0xf00d4b5d,"changeOwner(address _from, address _to)"

### Get Event Logs for a specific address

In [ ]:
# Events usually contain information about specific actions that occurred in a smart contract,
# such as token transfers, contract creations, or other significant events.

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'logs', # Module for account-related actions
    'action':'getLogs', # Action to get the account balance
    'address':'0xbd3531da5cf5857e7cfaa92426877b022e612cf8', # contract address
    'startblock':12878196, # Tag to specify the latest block
    'endblock':12878196, # Tag to specify the latest block
    'apikey':ETHERSCAN_API_KEY # API Key for Etherscan
}
r = requests.get(etherscan_url, params=params) # Making the GET request to Etherscan API
r.raise_for_status() # Raise an error for bad responses (4xx or 5xx status codes)
data = r.json() # Parsing the JSON response

In [13]:
# Display the data
print(f'API Response:\n{json.dumps(data, indent=4)}')

API Response:
{
    "status": "1",
    "message": "OK",
    "result": [
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000e9da256a28630efdc637bfd4c65f0887be1aeda8"
            ],
            "data": "0x",
            "blockNumber": "0xc47993",
            "blockHash": "0x13e906e02f1139e192dd23116e06275cc6d5e5a3447cb9e8085b1a041283ff92",
            "timeStamp": "0x60f963d9",
            "gasPrice": "0x4a817c800",
            "gasUsed": "0x415dfd",
            "logIndex": "0x8",
            "transactionHash": "0xe632f3e39c73b57a160c44451ff4ba8f19b80a0e60ab54a4e686a0f0687d81d4",
            "transactionIndex": "0x3"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258"
            ],
            "data": "0x000000000000000000000000e9da256a28630efdc637bfd4c65f0887be1aeda8",
            "blockNumber": "0xc47993",
            "blockHash": "0x13e906e02f1139e192dd23116e06275cc6d5e5a3447cb9e8085b1a041283ff92",
            "timeStamp": "0x60f963d9",
            "gasPrice": "0x4a817c800",
            "gasUsed": "0x415dfd",
            "logIndex": "0x9",
            "transactionHash": "0xe632f3e39c73b57a160c44451ff4ba8f19b80a0e60ab54a4e686a0f0687d81d4",
            "transactionIndex": "0x3"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000e9da256a28630efdc637bfd4c65f0887be1aeda8",
                "0x0000000000000000000000000000000000000000000000000000000000000000"
            ],
            "data": "0x",
            "blockNumber": "0xc479f6",
            "blockHash": "0x62d9dff817862d975a478b8cba7c50342f0ec3f29977c6781188ca238871c3a0",
            "timeStamp": "0x60f96922",
            "gasPrice": "0x572365f42",
            "gasUsed": "0x1f7e3",
            "logIndex": "0xac",
            "transactionHash": "0x5de14778174290ec856c6f3bf0aff822a3e91a3c32749beca311bd109772dbe3",
            "transactionIndex": "0x3b"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000000"
            ],
            "data": "0x",
            "blockNumber": "0xc479f6",
            "blockHash": "0x62d9dff817862d975a478b8cba7c50342f0ec3f29977c6781188ca238871c3a0",
            "timeStamp": "0x60f96922",
            "gasPrice": "0x572365f42",
            "gasUsed": "0x1f7e3",
            "logIndex": "0xad",
            "transactionHash": "0x5de14778174290ec856c6f3bf0aff822a3e91a3c32749beca311bd109772dbe3",
            "transactionIndex": "0x3b"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa"
            ],
            "data": "0x000000000000000000000000e9da256a28630efdc637bfd4c65f0887be1aeda8",
            "blockNumber": "0xc4816e",
            "blockHash": "0x9d510559dba6ba79f2945ff241572d181f90cf64b51087d863c9560e74e09eb1",
            "timeStamp": "0x60f9ce26",
            "gasPrice": "0x49c2c0600",
            "gasUsed": "0x6fbd",
            "logIndex": "0x10c",
            "transactionHash": "0xb1614b67923d5fb8e3ab9b4112c39836e3b0b15195550643bac9cb5de7885957",
            "transactionIndex": "0x7f"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x0000000000000000000000009ccfd6d678d1b467fceb11cd115e6c7afa323460",
                "0x0000000000000000000000000000000000000000000000000000000000000001"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000001"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x1",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x0000000000000000000000009ccfd6d678d1b467fceb11cd115e6c7afa323460",
                "0x0000000000000000000000000000000000000000000000000000000000000002"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x2",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000002"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x3",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x0000000000000000000000009ccfd6d678d1b467fceb11cd115e6c7afa323460",
                "0x0000000000000000000000000000000000000000000000000000000000000003"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x4",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000003"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1d1a94a200",
            "gasUsed": "0x5f3c3",
            "logIndex": "0x5",
            "transactionHash": "0x644c8396d4ee9ba9a95af419a11fd2ee28bb7739f95eaeec8885d534f64f30b4",
            "transactionIndex": "0x"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000004"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x6",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000004"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x7",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000005"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x8",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000005"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x9",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000006"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xa",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000006"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xb",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000007"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xc",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000007"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xd",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000008"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xe",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000008"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0xf",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x0000000000000000000000000000000000000000000000000000000000000009"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x10",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0x645f26e653c951cec836533f8fe0616d301c20a17153debc17d7c3dbe4f32b28",
                "0x0000000000000000000000000000000000000000000000000000000000000009"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x11",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x000000000000000000000000dd74a5f502167c1bdd88968d058834170175277b",
                "0x000000000000000000000000000000000000000000000000000000000000000a"
            ],
            "data": "0x",
            "blockNumber": "0xc4816f",
            "blockHash": "0xe897c2ce122535355e414dca231821dfb874f36408e77fe1dd68f9b4d3edffd8",
            "timeStamp": "0x60f9ce31",
            "gasPrice": "0x1a13b86000",
            "gasUsed": "0x12821a",
            "logIndex": "0x12",
            "transactionHash": "0x4e35a1d2ccd409d1f5598c2b41060ffcfbf19d41054635e048c35a8f6d508ef0",
            "transactionIndex": "0x1"
        },
        {
            "address": "0xbd3531da5cf5857e7cfaa92426877b022e612cf8",
            "topics": [

In [15]:
df = pd.DataFrame(data['result']) # Converting the logs to a pandas DataFrame

df.head()

,address,topics,data,blockNumber,blockHash,timeStamp,gasPrice,gasUsed,logIndex,transactionHash,transactionIndex
0,0xbd3531da5cf5857e7cfaa92426877b022e612cf8,[0x8be0079c531659141344cd1fd0a4f28419497f9722a...,0x,0xc47993,0x13e906e02f1139e192dd23116e06275cc6d5e5a3447c...,0x60f963d9,0x4a817c800,0x415dfd,0x8,0xe632f3e39c73b57a160c44451ff4ba8f19b80a0e60ab...,0x3
1,0xbd3531da5cf5857e7cfaa92426877b022e612cf8,[0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f...,0x000000000000000000000000e9da256a28630efdc637...,0xc47993,0x13e906e02f1139e192dd23116e06275cc6d5e5a3447c...,0x60f963d9,0x4a817c800,0x415dfd,0x9,0xe632f3e39c73b57a160c44451ff4ba8f19b80a0e60ab...,0x3
2,0xbd3531da5cf5857e7cfaa92426877b022e612cf8,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0x,0xc479f6,0x62d9dff817862d975a478b8cba7c50342f0ec3f29977...,0x60f96922,0x572365f42,0x1f7e3,0xac,0x5de14778174290ec856c6f3bf0aff822a3e91a3c3274...,0x3b
3,0xbd3531da5cf5857e7cfaa92426877b022e612cf8,[0x645f26e653c951cec836533f8fe0616d301c20a1715...,0x,0xc479f6,0x62d9dff817862d975a478b8cba7c50342f0ec3f29977...,0x60f96922,0x572365f42,0x1f7e3,0xad,0x5de14778174290ec856c6f3bf0aff822a3e91a3c3274...,0x3b
4,0xbd3531da5cf5857e7cfaa92426877b022e612cf8,[0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8a...,0x000000000000000000000000e9da256a28630efdc637...,0xc4816e,0x9d510559dba6ba79f2945ff241572d181f90cf64b510...,0x60f9ce26,0x49c2c0600,0x6fbd,0x10c,0xb1614b67923d5fb8e3ab9b4112c39836e3b0b1519555...,0x7f

### Get ERC-20 Token Supply by ContractAddresses

In [16]:
params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'stats', # Module for account-related actions
    'action':'tokensupply', # Action to get the token supply
    'contractaddress':'0x6b175474e89094c44da98b954eedeac495271d0f', # Contract address for DAI token
    'apikey':ETHERSCAN_API_KEY # API Key for Etherscan
}

response = requests.get(url=etherscan_url, params=params) # Making a GET request to the Etherscan API with the specified parameters
response.raise_for_status()
data = response.json() # Parsing the JSON response from the API

# Display the data
print(f'API Response:\n{json.dumps(data, indent=4)}')

API Response:
{
    "status": "1",
    "message": "OK",
    "result": "3792764745461665128048293474"
}

In [20]:
# Convert the token supply from Wei to Ether
token_supply_wei = int(data['result']) # Extracting the token supply in Wei from the response
token_supply_ether = token_supply_wei / 10**18 

print(f'Token Supply in Ether: {token_supply_ether:,.2f} DAI') # Displaying the token supply in Ether

Token Supply in Ether: 3,792,764,745.46 DAI

### Get ERC-20 Token Account Balance for Token Contract Address

In [22]:
# Returns the current balance of a specific address for a specific ERC-20 token contract
# This is similar to the previous example, but we are using a different action to get the balance of a specific token for a specific address.

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'account', # Module for account-related actions
    'action':'tokenbalance', # Action to get the token balance
    'contractaddress':'0x6b175474e89094c44da98b954eedeac495271d0f', # Contract address for DAI token
    'address':'0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae', # Address to get the token balance for
    'tag':'latest', # Tag to specify the latest block
    'apikey':ETHERSCAN_API_KEY # API Key for Etherscan
}

try:
    response = requests.get(url=etherscan_url, params=params) # Making a GET request to the Etherscan API with the specified parameters
    response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx status codes)
    data = response.json() # Parsing the JSON response from the API

except requests.exceptions.HTTPError as err:
    print(f'HTTP error occurred: {err}')

In [23]:
# display the data
print(f'API Response:\n{json.dumps(data, indent=4)}') # Displaying the API response in a formatted JSON structure

API Response:
{
    "status": "1",
    "message": "OK",
    "result": "0"
}

### Gas Tracker Metrics

In [24]:
# Gas oracle API provides real-time gas prices for Ethereum transactions.
# Gas Oracle prices (for priority fees)
# The gas prices are returned in Gwei, which is a subunit of Ether (1 Ether = 10^9 Gwei).

params = {
    'chainid':1, # Chain ID for Ethereum Mainnet
    'module':'gastracker', # Module for gas tracker actions
    'action':'gasoracle', # Action to get the gas oracle prices
    'apikey':ETHERSCAN_API_KEY
}

response = requests.get(url=etherscan_url, params=params)
response.raise_for_status() # Raises an HTTPError for bad responses (4xx or 5xx status codes)
data = response.json() # Parsing the JSON response from the API

print(f'API Response:\n{json.dumps(data, indent=4)}') # Displaying the API response in a formatted JSON structure

API Response:
{
    "status": "1",
    "message": "OK",
    "result": {
        "LastBlock": "23099362",
        "SafeGasPrice": "0.403509126",
        "ProposeGasPrice": "0.403532347",
        "FastGasPrice": "0.482509126",
        "suggestBaseFee": "0.403509126",
        "gasUsedRatio": "0.460033980574326,0.232118914623056,0.93550704742256,0.459418422222222,0.528891133333333"
    }
}